### ISSUE TITLE
Error with jest in version 3.0.0

### ISSUE THREAD

**Issue by franciscofabian** [d3/d3-format#115]
Since the latest version 3.0.0, jest throws an error when `d3-format` is imported.

The error is
```
    /user/test/my-app/node_modules/d3-format/src/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export {default as formatDefaultLocale, format, formatPrefix} from "./defaultLocale.js";
                                                                                             ^^^^^^
```

It happens importing it either as `const format = require('d3-format')` or as `import { format } from 'd3-format'`.
The build works fine and also in development mode, it is only running tests with jest. It didn't happen with version 2.0.0.

**Comment by mbostock** [comment]
Please read [the release notes](https://github.com/d3/d3-format/releases/tag/v3.0.0) and in particular Sindre Sorhus’ FAQ:

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

Sindre Sorhus has nicely provided you with some [Jest-specific advice](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#im-having-problems-with-esm-and-jest) and also politely reminds you that this is “not the place to ask ESM/TypeScript/Webpack/Jest/ts-node/CRA support questions.”
