### ISSUE TITLE
`"c"` format does not work as expected

### ISSUE THREAD

**Issue by ethanabrooks** [d3/d3-format#116]
According to the docs:
> c - converts the integer to the corresponding unicode character before printing

In my code,
```
console.log(format("c")(97));
```
Just prints 97.
I was expecting something along the lines of python:
```
>>> chr(97)
'a'
```

**Comment by Fil** [comment]
In C, python and PHP printf("%c", 97) give "a". In https://github.com/d3/d3-format/blob/ff87892bd861f9d8f386b0ea2e149da6e61a7440/src/formatTypes.js#L8 it gives "97".
The tests are only for a 1-char string input, so it looks like an oversight.

**Comment by mbostock** [comment]
The code is doing what is intended here, but it looks like we forgot to update the documentation accordingly. This was changed in https://github.com/d3/d3-format/commit/e247671b89d78fa27106bafede4d7703c5ac1eb0.

**Comment by ethanabrooks** [comment]
I see. Is there a way to do achieve the same effect as python's `chr` function with d3-format?

**Comment by mbostock** [comment]
> Is there a way to do achieve the same effect as python's `chr` function with d3-format?

Not currently, but you could use String.fromCharCode(97) in conjunction with type `c`.
