### ISSUE TITLE
Hot reload is complaining about named functions in nextjs

### ISSUE THREAD

**Issue by cipriancaba** [d3/d3-format#117]
`./node_modules/d3-format/src/index.js`
Anonymous function declarations cause Fast Refresh to not preserve local component state.
Please add a name to your function, for example:

Before
export default function () { /* ... */ }

After
export default function Named() { /* ... */ }

A codemod is available to fix the most common cases: https://nextjs.link/codemod-ndc

This was referenced in #114 as well

**Comment by Fil** [comment]
same answer as in #114: that's an issue with next.js not with d3-format

**Comment by cipriancaba** [comment]
Hi @Fil , thanks for the quick feedback on this. Just to clarify that this issue is related to anonymous function declarations rather than any module discussion

I am willing to open a PR that will change the default anonymous functions to named functions. The functionality will be exactly the same, but will help other frameworks that rely on fast refresh, will help debugging and so on.

**Comment by fabienheureux** [comment]
@Fil don't you think @cipriancaba suggestion would help make d3 works properly for more users out there ? 
Next.js is a widely used technology in React ecosystem and it does not look like this change would break features on d3's side.

**Comment by Fil** [comment]
From the [wiki](https://github.com/d3/d3/wiki#supported-environments): "D3 is not a compatibility layer". Please help fix your favorite dev environments so they do the right thing. I'm locking this issue as a duplicate of #114, which has more details including a workaround.
