### ISSUE TITLE
Missing d3-format.min.js 

### ISSUE THREAD

**Issue by ityoung2016** [d3/d3-format#124]
I have been using d3-format.min.js (v1.4.4) for a long time. I thought it time to look for an update but I cannot find one. I have found d3.min.js (v7.1.1) which seems to contain d3-format as a subset. Can I simply use d3.min.js as a somewhat-larger alternative or is there a downloadable latest version of d3-format.min.js?

**Comment by ityoung2016** [comment]
Thank you! I am not sure why it is “hidden” away; it is a very useful module.

**Comment by Fil** [comment]
There's a link on the main page, in the "Installing" section
https://github.com/d3/d3-format#installing
