### ISSUE TITLE
Undefined Import in Next.js

### ISSUE THREAD

**Issue by frankfka** [d3/d3-format#125]
I am attempting to use d3-format without d3 in a Next.js app. I'm importing using `import d3 from 'd3-format'` but I am getting that the d3 object is undefined, likely because the import is happening serverside? Is there a workaround?

**Comment by mbostock** [comment]
This library does not provide a default export. You need to say `import * as d3 from "d3-format"` or just import the specific symbols you need, such as `import {format} from "d3-format"`.
