### ISSUE TITLE
Using custom units in d3-format

### ISSUE THREAD

**Issue by 7vikpeculiar** [d3/d3-format#128]
I am trying to use Lakhs (10^5) and Crores (10^7) which are used in India for currency; instead of the SI units that d3 supports by default. 

Is there a way to change the units from default in D3 to achieve this ?

**Comment by Fil** [comment]
Yes you can use the locale en-IN
https://github.com/d3/d3-format/blob/main/locale/en-IN.json

<img width="768" alt="Capture d’écran 2022-04-08 à 10 55 32" src="https://user-images.githubusercontent.com/7001/162401812-6ca5fa7c-0fcb-42c2-a4c0-76be7d572e25.png">

**Comment by 7vikpeculiar** [comment]
@Fil I want to use the units too, if that makes sense ... i.e `1,23,45,67` as `1.23 Cr` for example. I am able to change the comma system, but I am not able to add my own units

**Comment by Fil** [comment]
One example is not enough to specify everything; you might want to create a function that will route the value to the correct format, depending on its magnitude.
