### ISSUE TITLE
Bower installable?

### ISSUE THREAD

**Issue by ambischof** [d3/d3-format#13]
It's not registered on Bower, and if you point it to the repository, it doesn't pull the built version. (only worked with absolute link to package)

Is this just not implemented yet or is it intentional because it's not ready?

**Comment by mbostock** [comment]
It’s ready; it’s just that I don’t use Bower, so I haven’t bothered to register this or module (or any of the numerous other D3 modules).

**Comment by mbostock** [comment]
Registered as `d3-format`.

**Comment by missingdays** [comment]
What about building module after it is installed with Bower, just as it is done with node?
It would be cool to install it with Bower and be able to use it in browsers, that have no support for ES6.

**Comment by mbostock** [comment]
I only support npm and GitHub releases as publishing systems. Please see this issue for additional context:

https://github.com/d3/d3-color/issues/28
