### ISSUE TITLE
Is it possible to support locale zh-TW?

### ISSUE THREAD

**Issue by minaseem** [d3/d3-format#130]

**Comment by mbostock** [comment]
Yes, contributions welcome.

**Comment by minaseem** [comment]
Raised a PR - https://github.com/d3/d3-format/pull/131

Please let me know in case you have suggestions. 

Thanks!

**Comment by minaseem** [comment]
@mbostock PR - https://github.com/d3/d3-format/pull/131 has been pending since long. This fix is important for us. Can you help in getting it merged?
