### ISSUE TITLE
Should functions be named across `d3-*` ?

### ISSUE THREAD

**Issue by gabrielbahniuk** [d3/d3-format#133]
Hi there, 

I have a Next.js project where I have some charts and use a few d3 libraries like d3-format, d3-selection, etc - all of that in some old version, 1.4.1 if I remember correctly.

A few days ago there was a high vulnerability and I had to update to v3. Here it was also required to add `d3-*` into `transpileModules` from webpack configuration due to ESM incompatibility.

Now I have the warning, not only for `d3-format` but for the others as well when I run my Cypress tests:

```
my-project/node_modules/d3-format/src/precisionFixed.js
Anonymous function declarations cause Fast Refresh to not preserve local component state.
Please add a name to your function, for example:
Before
export default function () { /* ... */ }
After
export default function Named() { /* ... */ }
```

Unfortunately, my tests are always failing due to Next.js Fast Refresh and looking into the src code from `d3-format/src/precisionFixed.js` I just found out this code:

```js
import exponent from "./exponent.js";

export default function(step) {
  return Math.max(0, -exponent(Math.abs(step)));
}
```

Question: does that make any sense to add names to functions here (and in a few other places from `d3-*`) libs?

**Comment by mbostock** [comment]
It’s a bit obnoxious of tooling to place this burden on library authors in this way, but at any rate, I’ll probably switch everything to use named instead of default exports at some point. It’s not high on my priority list, though, sorry.

**Comment by gabrielbahniuk** [comment]
> It’s a bit obnoxious of tooling to place this burden on library authors in this way, but at any rate, I’ll probably switch everything to use named instead of default exports at some point. It’s not high on my priority list, though, sorry.

@mbostock it was only a question as I am investigating solutions for the problem I have, not placing a burden on anyone, sorry if you understood that way. Thank you for the answer.

**Comment by mbostock** [comment]
@gabrielbahniuk My comment was directed at Next.js (or maybe React Fast Refresh? wherever the warning comes from). It seems strange that it can’t just assign an arbitrary name like “_default” and make anonymous default exports work out of the box. My objection is that JavaScript provides a standard language feature (default exports) and it’s a shame when tooling doesn’t support the language standard completely, and then the burden is placed on library authors to rewrite their code to satisfy the limitations of popular tooling.

**Comment by gabrielbahniuk** [comment]
@mbostock oh, i misinterpreted and agree with you - there are a few `d3-*` packages, but imagine if there were 100+ packages, I would have to change each one because of 1 framework - that doesn't sound right (even though naming functions seem correct, but not for this purpose). 

I will continue my investigation and try out other solutions as well. 

As a side note: not sure if that would be ok for you but I would be fine to open PRs to replace non-named by named functions in default exports.
