### ISSUE TITLE
The minus sign generated by d3.format not compatible with SVG 

### ISSUE THREAD

**Issue by veli-gasparovic** [d3/d3-format#143]
Noticed the problem while building a "defs" with a gradient. I wanted the "y1" attrib to be negative and used this:

`.attr(
      "y1",
      d3
        .format(".0%")(-(margin.top + margin.bottom) / height)
    )`

However, the resulting string wasn't properly rendered:
y1="−18%"

Then I tried hardcoding it, only to notice it's a different character:

y1="-18%"

Not sure if that's a general problem, or browser related (I used Brave). I ended replacing:

` d3
        .format(".0%")(-(margin.top + margin.bottom) / height)
        .replace(/−/g, "-")`

**Comment by mbostock** [comment]
Working as intended. d3-format is for human consumption, not for generating an SVG attribute.
