### ISSUE TITLE
d3 format transfer minus(-) to ascii 8722 code

### ISSUE THREAD

**Issue by sharpFD** [d3/d3-format#144]
except transfer -8888 to -8,888, I found that d3 format transfer the minus(ascii 45) to an unexcepted code which ascii code is 8722

except -8,888
actual −8,888

u can pick the minus to compare
<img width="153" alt="image" src="https://github.com/d3/d3-format/assets/18305837/8b758cdb-8707-43c0-8c50-e3898a32dc73">

**Comment by Fil** [comment]
This works correctly with a "minus sign" character, which is not the same as the minus operator; see https://www.compart.com/en/unicode/U+2212

**Comment by sharpFD** [comment]
> This works correctly with a "minus sign" character, which is not the same as the minus operator; see https://www.compart.com/en/unicode/U+2212

I know it's difference between Hyphen-Minus and Minus Sign. But I can't understand why should use Hyphen-Minus which may make excel cell calculate error. or can u provide a optional parameter for users to choose freely?


Additionally, I found some popular number format dependencies and make a demo. u can found the difference between d3 format and other utils.

https://codesandbox.io/p/sandbox/d3format-x2shz3?file=%2Fsrc%2Findex.mjs

**Comment by mbostock** [comment]
We use a minus sign because it is the better typographical choice. d3-format is for formatting numbers for human consumption, not for Excel calculations. Why not use a different library if you want a hyphen minus?
