### ISSUE TITLE
d3 convert 0.996 to 996m

### ISSUE THREAD

**Issue by chauhansudhir** [d3/d3-format#19]
d3.format('.3s') format method convert points to million range.
https://jsfiddle.net/64fde19v/

Not sure if I am doing something wrong.

**Comment by mbostock** [comment]
The *m* [SI prefix](https://en.wikipedia.org/wiki/Metric_prefix#List_of_SI_prefixes) stands for milli, [‰](https://en.wikipedia.org/wiki/Per_mille), thousandths. Thus 996m = 996 / 1000 = 0.996.

**Comment by mbostock** [comment]
(It’s the M SI prefix, for mega, that means millions.)
