### ISSUE TITLE
percentage format issue

### ISSUE THREAD

**Issue by dobingo** [d3/d3-format#26]
it seems we could only get ".1%" format correctly and we could not get more decimal digits format for percentage such as ".11%" or ".1111%" format.

	$("#testValue").append( ".11% 1234.56789:" + "<p>" + d3.format(".11%")(1234.56789) + "</p>");//123456.78900000000%
	$("#testValue").append( ".1% 1234.56789:" + "<p>" + d3.format(".1%")(1234.56789) + "</p>");//123456.8%
	$("#testValue").append( ".1111% 987.654321:" + "<p>" + d3.format(".1111%")(987.654321) + "</p>");//98765.43210000000544823706%
	$("#testValue").append( ".1% 987.654321:" + "<p>" + d3.format(".1%")(987.654321) + "</p>");//98765.4%
	$("#testValue").append( ".11% 987.654321 with round:" + "<p>" + d3.format(".11%")(d3.round(987.654321,4)) + "</p>");//98765.43000000001%
	$("#testValue").append( ".11% 987.654321 with round:" + "<p>" + d3.round(987.654321,4) + "</p>");//987.6543

**Comment by mbostock** [comment]
`.11%` means a precision of 11 digits. If you want two digits, use `.2%`.
