### ISSUE TITLE
Custom bundle via rollup is broken

### ISSUE THREAD

**Issue by Turbo87** [d3/d3-format#28]
I'm trying to generate a custom bundle of D3 v4 using rollup:

https://github.com/Turbo87/rollup-d3-issue

Running `npm run build` (or `rollup -c`) will produce a bundled file at `dist/d3.js` which looks fine on first glance. It includes the following function call:

```js
defaultLocale({
  decimal: ".",
  thousands: ",",
  grouping: [3],
  currency: ["$", ""]
});
```

but the `defaultLocale()` function is not defined anywhere in the bundle even though it's in the original code (at https://github.com/d3/d3-format/blob/v1.0.2/src/defaultLocale.js).

Note that if I add `export { formatDefaultLocale } from 'd3-format';` to the `d3.js` file we can work around this issue. This is not a good long-term solution though.

Cross-posted this as https://github.com/rollup/rollup/issues/970

**Comment by mbostock** [comment]
Thanks for filing an issue. This is clearly a Rollup bug, so I’ll close this and reply over there if I have any insight. Sorry for the inconvenience.
