### ISSUE TITLE
Unable to import from d3-format with rollup

### ISSUE THREAD

**Issue by darthmall** [d3/d3-format#29]
I was trying to use the D3 microlibraries with rollup, but once I imported something from d3-scale, I started getting an error about `defaultLocale` being an undefined function. I dug into it and it seems that rollup is importing the call to `defaultLocale` in `defaultLocale.js` but not the function definition.

I set up a test project that illustrates the problem. https://github.com/darthmall/rollup-d3-format-test

**Comment by mbostock** [comment]
Please see rollup/rollup#967.

**Comment by darthmall** [comment]
Thanks, @mbostock. Sorry for the bother.
