### ISSUE TITLE
RequireJS

### ISSUE THREAD

**Issue by dr-martin** [d3/d3-format#30]
I want to load this module only, with RequireJS, does not work. The d3 object is invalid unless i receive the variable as "d3", but this not is a total solution because: What happen if i want load more individually modules?. This is my code:
`define(['d3_format'], function(d3_format){
	console.log(d3)
});`
And the message is:
`d3 is not defined`

**Comment by mbostock** [comment]
If you require this library, the name of the required module is whatever parameter name your callback function uses; in your example, that’s `d3_format`. So you’ll need to use that instead of the shared `d3` object which only applies in a vanilla environment.
