### ISSUE TITLE
default Arabic Locales Format are missing at d3-format

### ISSUE THREAD

**Issue by Ashamandi** [d3/d3-format#36]
Hello, This is Ayah Shamandi, bidi developer -Globalization team at IBM Egypt, we are responsible for adding globalization and bidi featuers at open source technologies which IBM products used.

and we noticed that D3.format supports different locales except Arabic ones, so I opened this isssue to request adding the missing ones.

and here is the list of locales I am going to add:

- Arabic(Algeria)                         - Arabic (Bahrain)                       - Arabic (Chad)
- Arabic (Comoros),                    - Arabic (Djibouti),                     - Arabic (Egypt),
- Arabic (Eritea),                          - Arabic (Iraq),                           - Arabic (Israel), 
- Arabic (Jordan),                        - Arabic(Kuwait),                        - Arabic (Lebanon), 
- Arabic (Libya) ,                         - Arabic(Mauritania),                  - Arabic (Morocco), 
- Arabic (Oman),                        - Arabic (Palestinian Territories), 
- Arabic(Qatar),                          - Arabic (Saudi Arabia),             - Arabic ( Somalia), 
- Arabic (South Sudan),             - Arabic (Sudan),                        - Arabic (Syria), 
- Arabic (Tunisia),                      - Arabic(United Arab Emirates), 
- Arabic (Western Sahara),        - Arabic (World),                         - Arabic (Yemen).

**Comment by mbostock** [comment]
Sounds good. You are welcome to submit new locales in a pull request. Thank you!
