### ISSUE TITLE
How can I rebuild d3-format after any change?

### ISSUE THREAD

**Issue by Ashamandi** [d3/d3-format#39]
## Just a Question?
I have created a PR #38 to push the new Arabic locales based on issue #36  and created test files to test them but I need to rebuild d3-format locally before pushing the test files to make sure that everything is fine but I do not know how ? the READMe file does not illustrate how to re-generate d3.format file after making any change.

**Comment by curran** [comment]
The build and test scripts are in package.json here:

https://github.com/d3/d3-format/blob/master/package.json#L24

To rebuild locally and run the tests, first run `npm install` to install dependencies, then run `npm test`.

**Comment by mbostock** [comment]
Also note that the locale files, aside from a handful that have tests, are not involved in the build process. They are typically loaded in the client to create a new locale object or set the default locale; I have added [an example to the README](https://github.com/d3/d3-format/blob/master/README.md#installing).
