### ISSUE TITLE
option to remove trailing zeros for "s" type prefix

### ISSUE THREAD

**Issue by HaithamMaya** [d3/d3-format#44]
Currently if I do `d3.format("0.3s")(myString)` it will add trailing zeros, however in the case when working with population-based data, it adds trailing zeroes for data involving whole numbers (for example, 9 -> 9.00)

**Comment by mbostock** [comment]
The only option that supports trimming trailing zeroes after the decimal place is the `​` (none) type. This is not supported with other format types. So, you’ll either need to look at the [formatDefault implementation](https://github.com/d3/d3-format/blob/master/src/formatDefault.js) and roll your own, or use the none type while manually adding the desired SI unit.

**Comment by HaithamMaya** [comment]
@mbostock would you accept a PR for this?

**Comment by tracyhenry** [comment]
Removing trailing zeros is quite useful. Wonder why there is no intent to support it.

**Comment by mbostock** [comment]
@tracyhenry This issue is almost four years old. Support for removing trailing zeroes was [added in 1.3.0](https://github.com/d3/d3-format/releases/tag/v1.3.0). Please read the README regarding the `~` option.

**Comment by tracyhenry** [comment]
> @tracyhenry This issue is almost four years old. Support for removing trailing zeroes was [added in 1.3.0](https://github.com/d3/d3-format/releases/tag/v1.3.0). Please read the README regarding the `~` option.

Yep just found that. Thanks!
