### ISSUE TITLE
Decimal rounding down on 5 instead of up

### ISSUE THREAD

**Issue by kevlarr** [d3/d3-format#48]
When rounding to one decimal place, **17.45** should round to **17.5** but is instead rounding to **17.4**.

```
> d3.format('.1f')(17.450)
"17.4"
> d3.format('.1f')(17.451)
"17.5"
```

**Comment by mbostock** [comment]
This is the expected behavior and is a consequence of IEEE 754 being binary floating point.

```
> (17.450).toFixed(1)
"17.4"
> (17.451).toFixed(1)
"17.5"
> (17.450).toFixed(20)
"17.44999999999999928946"
```

As you can see, the value 17.45 in JavaScript is not exactly 17.45, but slightly below, and thus the rounded value to one decimal place is 17.4.

See also the discussion in #27.

**Comment by kevlarr** [comment]
@mbostock Ah, I searched but did not find that thread. Excellent resource, thank you!
