### ISSUE TITLE
Access to default locale

### ISSUE THREAD

**Issue by Lacroute** [d3/d3-format#49]
It could be usefull to have getter to the default locale. Something like `d3.formatLocale()` without args could do the job.

Why?
Because when you work on multilang graphics, it's simplier to handle a locale object, update it, and call `locale.format` than the global `format` function, and always setting the default locale of d3. For now I recreate the locale object with the `format` and `formatPrefix` functions. But it's something that the lib could do.

I can make the PR if you agree.

**Comment by mbostock** [comment]
Closing to inactivity, and this feels easy enough to do yourself that I don’t see a strong need to provide a convenience method in the library itself.

```js
const defaultFormat = {
  format: d3.format,
  formatPrefix: d3.formatPrefix
};
```
