### ISSUE TITLE
D3-format version 3 working broken in version 4 

### ISSUE THREAD

**Issue by jainswapnil90** [d3/d3-format#52]
var value = 124.256
**d3.format(',.f')** was returning the actual value on 
format(value) =124.256

but in version 4 same function is broken

> d3.min.js:2 Uncaught Error: invalid format: ,.f
>     at new Xe (d3.min.js:2)
>     at He (d3.min.js:2)
>     at Object.n [as format] (d3.min.js:2)
>     at Object.locale.decimalFormat (com01.fwk:165)

**Comment by mbostock** [comment]
As the error tells you, that is an invalid format: you are using `.` without specifying a precision. If you want to specify a precision, using something like `,.3f`; if you don’t want to specify a precision, use `,f`. Please read the API reference for [*locale*.format](https://github.com/d3/d3-format/blob/master/README.md#locale_format) on how to specify number formats.
