### ISSUE TITLE
Currency suffix position is wrong when using Si-prefix format

### ISSUE THREAD

**Issue by borisrorsvort** [d3/d3-format#53]
The test only test currency with prefix as default https://github.com/d3/d3-format/blob/5b9efdeb9a63b4fb72d10500d13034f6a3eca3b2/test/format-type-s-test.js#L93

When using the fr  default Locale, currency is suffix but is wrongly placed before the Si-prefix.
 
`format("$.2s")(800000000) => 800 €M`

Expected output is `800M €`

**Comment by mbostock** [comment]
Fixed in 1.2.2.

**Comment by borisrorsvort** [comment]
Thanks for the quick fix! :+1:
