### ISSUE TITLE
Trim insignificant .00 on SI prefix format

### ISSUE THREAD

**Issue by vasturiano** [d3/d3-format#54]
I'm trying to get this number formatting:
`1000` -> `'1k'`
`1500` -> `'1.5k'`

But doing `format('s')` gives me instead:
`1000` -> `'1.00000k'`
`1500` -> `'1.50000k'`

I can try to remove the fixed precision (`format('.0s')`), but that will break it for the 2nd number:
`1000` -> `'1k'`
`1500` -> `'2k'`

That seems to be happening because the default precision is set to 6 fixed points, and the minimum is 1. So `.0s` really acts as `.1s`, if I'm reading this section correctly:
https://github.com/d3/d3-format/blob/master/src/locale.js#L46

This feature seems to be showing up in the tickFormat block too:
https://bl.ocks.org/mbostock/9764126

In the middle axis (`format('.0s')`), the top values show as repeated `2M` and `1M` due to the rounding, while ideally they would show `1.2M`, `1.4M`, etc. 

Would be nice if there's an easy option to remove insignificant trailing 0s, regardless of the type. This option exists for type 'g' (type none), but not for SI and other modes.

Or maybe there's a way to do this currently that I didn't realise. :)

**Comment by alexsapps** [comment]
Same here. I want to set the number of decimal places rather than number of significant digits with SI prefixes, and I don't want to use formatPrefix because I still want the prefix to be dynamically computed for each number.

**Comment by mbostock** [comment]
Under the current design, we’d need a new format type to support this, akin to the difference between the *none* specifier and *g* but for *s*.

Or, we’d need to extend the format specifier syntax so that trimming of insignificant zeroes can be applied generically to any format type (any format type that makes sense, I suppose…).

**Comment by vasturiano** [comment]
@mbostock I like your suggestion to extend the syntax so that trimming can be applied generically to all types. Seems like the most reasonable option. PR open: #57.
