### ISSUE TITLE
decimal to fraction

### ISSUE THREAD

**Issue by AbdulBsit** [d3/d3-format#55]
how to tickformat decimal to fraction?

**Comment by curran** [comment]
Can you please give an example of what you mean?

**Comment by AbdulBsit** [comment]
![whatsapp image 2018-03-20 at 6 24 32 pm](https://user-images.githubusercontent.com/32831612/38100769-eb7fcd22-339b-11e8-9b30-1142a8802eb6.jpeg)
wanna to make plot like this taking y-axis as of fraction format

**Comment by curran** [comment]
How is the data formatted for the fraction vallues?

This tick format should work out of the box using `d3.scalePoint`, assuming the data values are strings like "6/6", "6/9", "6/12", and you pass in the scale domain in the correct order, like `[ "6/6", "6/9", "6/12" ]`.

**Comment by AbdulBsit** [comment]
its just good for for a small amount of data
but not possible to treat as labels for the large amount of data
