### ISSUE TITLE
Add option to use JS Intl.NumberFormat

### ISSUE THREAD

**Issue by tiberiuzuld** [d3/d3-format#58]
Hello,

If possible add option to use the [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) instead of the current format.

Currently for the charts I use the d3-format and for the rest of the application I use the `Intl.NumberFormat`

If is possible to create an option to set the default locale I want to use to format the numbers with the Intl API.
```js
d3.formatDefaultLocaleIntl('en-GB'); // if empty use the browser locale
```

P.S. also for the https://github.com/d3/d3-time-format to do the same would be great.

Thanks

**Comment by mbostock** [comment]
Wouldn’t you just use Intl.NumberFormat directly, instead of using d3-format? I’m afraid I don’t understand what you’re asking for.

**Comment by tiberiuzuld** [comment]
Hmm didn't thinking it through that you can pass any other function to the [scale.tickFormat](https://github.com/d3/d3-scale/blob/master/README.md#continuous_tickFormat) and format as you want.

Sorry for the wasted time.
