### ISSUE TITLE
Invalid Format ("~s")  is found in the documentation

### ISSUE THREAD

**Issue by Vivalldi** [d3/d3-format#59]
In the example found in the documentation `"~s"`is a valid format.
```
d3.format("~s")(1500); // "1.5
```

However upon using this with d3.v5 one is then presented with `Uncaught Error: invalid format: ~s`

**Comment by mbostock** [comment]
The `~` option was [added in 1.3.0](https://github.com/d3/d3-format/releases/tag/v1.3.0), so I am closing this under the assumption that you are using an older version of d3-format.
