### ISSUE TITLE
feature request: format for PPM

### ISSUE THREAD

**Issue by RichardNeill** [d3/d3-format#66]
Consider a value recorded as "14 PPM defects" i.e. "14 defective parts per million".

The underlying value is 0.000014.  D3 currently shows this on the axis as "14u"  (the micro symbol).
When the axis title is "ppm defects", this actually implies "14 micro parts per million".
It would be helpful if it could display as "14 ppm" instead.

In other words, I'm proposing an additional "type" format, perhaps "u", which acts in the same way as "p", but multiplies by 1000000 and has a "ppm" sign.

Thanks very much :-)

**Comment by mbostock** [comment]
How about wrapping the format?

```js
const format = d3.format("d");
const formatPpm = value => format(value * 1e6) + " ppm";
formatPpm(0.000014) // "14 ppm"
```
