### ISSUE TITLE
Percent type (% / p) without multiplying by 100

### ISSUE THREAD

**Issue by jwmann** [d3/d3-format#68]
I can't really control what data is coming in so I'm getting floats like this e.g.: `34.21` to represent 34.21%. Except using the percentage hoverformats multiply that number by 100, outputting: 3421%

Is there a way to bypass that multiplication?

**Comment by mbostock** [comment]
There is not, but here are two workarounds:

1. Use `r` instead of `p`, or `f` instead of `%`.
2. Divide the values by 100 prior to calling d3.format with `p` or `%`.
