### ISSUE TITLE
SI-prefix changes data value

### ISSUE THREAD

**Issue by silvanaweb** [d3/d3-format#72]
I have the following input data:
`ticks = [-20, -15, -10, -5, 0, 5, 10, 15, 20]`

I use a format: `formatTickLabel = format(".1s")` applied to text:
```
lg.selectAll("text")
      .data(ticks)
      .enter()
      .append("text")
      .text(x => formatTickLabel(x));
```
Expected
I expect the ticks labels to be: -20  -15 -10 etc.

Actual
What I see is : -20  -20 -10 5 0 5 10 20 20.

**Comment by mbostock** [comment]
This is the expected behavior. The format `.1s` specifies one significant digit, so the value -15 (which requires two significant digits to display: 1 and 5) is rounded to -20.
