### ISSUE TITLE
Support default currency decimals

### ISSUE THREAD

**Issue by grassick** [d3/d3-format#78]
Difference currencies have different numbers of fractional digits to be shown. This is locale-specific. For example:

```
(3.4).toLocaleString("en", { style: "currency", currency: "USD" })
"$3.40"
```
Unfortunately, some locales have 3 digits (Iraq, Jordan, etc), some have 4 (Chile, Uruguay) and some have 0 (Paraguay, Rwanda). Since that information doesn't seem built in to the locale definition, I'm not clear on how to display a currency value with the default number of digits.

**Comment by mbostock** [comment]
Per the README, the default precision is based on the *type* specifier and is not affected by the *symbol* (if any):

> If the precision is not specified, it defaults to 6 for all types except (none), which defaults to 12.

So, you’ll need to specify the desired precision yourself. Or use the Intl.NumberFormat API instead of d3-format.
