### ISSUE TITLE
Cannot trim insignificant digits when specifying decimal points

### ISSUE THREAD

**Issue by mofojed** [d3/d3-format#80]
I'm not sure if there's another way to specify this, but when you specify the number of floating point digits you want to display, and to trim insignificant digits, it only applies the trim. This seems inconsistent - if the max floating points are specified, the trim should be applied after limiting the decimal points

Eg.
```
d3.format('00.4f')(72.210000000000) // Outputs '72.2100'
d3.format('00.~4f')(72.210000000000) // Outputs '72.21'
d3.format('00.4f')(72.210000000001) // Outputs '72.2100'
d3.format('00.~4f')(72.210000000001) // Outputs '72.210000000001', expected '72.21'
```

[Codepen here](https://codepen.io/mofojed/pen/ExxRNpR)

**Comment by mbostock** [comment]
Your codepen is using d3 3.x, which doesn’t support this feature. Try upgrading to d3 5.x or d3-format 1.x.

https://observablehq.com/d/28575fe43d74feab
