### ISSUE TITLE
Stating figure as a multiple (e.g. "#.#X")?

### ISSUE THREAD

**Issue by ajsnyder** [d3/d3-format#88]
Hi!  I'm using a data viz tool that allows me to specify a custom number format using d3-format.  For my dashboard, I have a table currently that has a column specifying an entity (let's say students for this example) and another column that specifies a number (lets say test score).  

For the test scores column, I am stating the scores as figures relative to the average test score. 
 For example, let's say the average test score was 70, Student A got a 90, Student B got a 50 and Student C got an 70  Dashboard would populate as follows:

Student | Relative Test Score
-------- | -------------------
Student A| 1.3
Student B | 1.0
Student C | 0.6

For the figures in the Relative Test Score column, I would like to add an "x" character in the end to denote that the figure is a multiple.  Something like this.

Student | Relative Test Score
-------- | -------------------
Student A| 1.3x
Student B | 1.0x
Student C | 0.6x

Is it possible for me to do this?

**Comment by mbostock** [comment]
Try this:

```js
const formatNumber = d3.format(".1f");

function formatMultiple(x) {
  return `${formatNumber(x)}×`;
}
```
