### ISSUE TITLE
Get parts rather than string

### ISSUE THREAD

**Issue by emattias** [d3/d3-format#93]
Is it possible to make `d3-format` output the result in parts, not as a string?

I would like to avoid getting the SI Prefix from the string 

Pseudo code of something like what I want:

```js
const formatter = d3.format('.2s')
formatter(10000) // => { number: 10, siPrefix: 'k' }
```

My use case is that I want to animate big numbers using [countUp](https://github.com/inorganik/countUp.js/).

## Example

I have the number `150000` and I want to animate it abbreviated as `150k`. Then I want to animate it from `0` to `150` so I give countUp `150`, not `150000`:

```js
const d3Formatter = d3.format('.2s')

new CountUp(
  myDomElement,
  150,
  {
    formattingFn: function (number) {
      return d3Formatter(number);
    }
  }
);
```

this results in `d3Formatter` getting `0` to `150` so no SI-prefix.. With my pseudo code I was thinking I could do something like:

```js
const d3FormatterInParts = d3.formatInParts('.2s');
const { number, siPrefix } = d3Formatter(150000);

new CountUp(
  myDomElement,
  150,
  {
    formattingFn: function (number) {
	  const { number, siPrefix } = d3Formatter(number);
      return number + siPrefix;
    }
  }
);
```

**Comment by mbostock** [comment]
No, this is not supported.

**Comment by emattias** [comment]
Ok and it wont be added? :)
