### ISSUE TITLE
Use B instead of G?

### ISSUE THREAD

**Issue by curran** [d3/d3-format#94]
One of the most common pieces of feedback I get from clients for visualizations that use the SI format is "What does G mean?" and "Why doesn't is use B for Billions?".

It's easy enough to do [string replacement](https://vizhub.com/curran/900cb204023748b9a8bdf2273bdefe03?edit=files&file=index.js#L54) with something like this:

```js
const yAxisTickFormat = number =>
  format('.1s')(number)
    .replace('G', 'B');
```

However, as I find myself doing this over and over in different projects, I wonder if it might be a sensible thing to build into `d3-format`. I thought I'd open this issue as a place to discuss ways to approach this.

Anyone else run into this issue?

Related: https://github.com/d3/d3-format/issues/71

**Comment by mbostock** [comment]
Changing this wouldn’t be backwards-compatible, and also muddies the feature definition, which is very clearly defined  to used SI prefixes. The way for this feature to proceed is a new format directive (something other than `s`), which is covered by #71. So I’m closing this as a duplicate, but I’d welcome input on that issue!

**Comment by curran** [comment]
Thanks!
